### PR TITLE
Min_Element_In_Array.java

### PR DESCRIPTION
**Pull request by VaibhavSatija10**
This is a program used to find the minimum element in an array containing user entered values.

### CODE REVIEW

**Comment by krishmurarka** [comment]
Please upload this file under HackerRank folder

**Comment by VaibhavSatija10** [comment]
I have uploaded this file in the hackerrank folder through another PR.
Please do have a look.

**Comment by krishmurarka** [comment]
okay merged ,Thank you for contributing

**Comment by VaibhavSatija10** [comment]
Thanks a lot.
It was a great learning curve!
Hope to contribute in many more projects in the field of Open Source in the near future.
Regards
Vaibhav

**Pull request closed without merging**
